### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by zqflash** [nzl5116190/Basisformer#10]
作者您好，我在调用MS时报了如下错误
l_neg = torch.bmm(logit_q.reshape(-1,self.N,self.k), logit_k.reshape(-1,self.N,self.k).permute(0,2,1)).reshape(-1,self.N) # (B,C*N,N)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [224, 16] but got: [32, 16].
请问该如何解决啊，谢谢。

**Comment by nzl5116190** [comment]
### **English Version**
Thank you for your feedback. Your issue is similar to Issue #8. The original code was designed for multivariate (M) and univariate (S) settings without considering the MS case, which is why this issue arises.

In the latest version of the code, we attempted to update the support for MS prediction, and you can download and use it. However, we are uncertain about the performance of our method in the MS context, and you may need to conduct your own tests.

The primary reason for this issue is that our approach considers the consistency between the past and future of the sequences and bases as a self-supervised loss. In the multivariate and univariate prediction settings, the past and future of each sequence correspond one-to-one, making the supervision meaningful. However, in the MS setting, the past of multiple sequences corresponds to the future of only one sequence, resulting in a non-one-to-one relationship. In the code, we only use a linear layer to map the scores of multiple sequences to a single sequence, which could pose some issues for supervision.

Additionally, under the MS conditions, the original normalization and denormalization operations cannot function correctly, as the channel dimensions for the past and future differ. Our model expects interactions between the sequences and bases to occur in a normalized space, which may also lead to a decline in performance.

We appreciate your understanding and support. Please feel free to reach out if you have further questions.

### **中文版本(Chinese Version)** 

感谢您的反馈。您的问题与问题#8 是相同的。原始代码是为多变量（M）和单变量（S）设置设计的，而没有考虑到MS的情况，这就是为什么会出现这个问题。

在目前最新版本的代码中，我们已尝试更新支持MS预测的部分，您可以下载并使用。然而，我们不确定我们的方法在MS上的性能，可能需要您进行实际的测试。

造成这种情况的主要原因是，我们的方法考虑了序列与基底之间过去和未来的一致性作为自监督损失。在多变量预测和单变量预测的设置下，每条序列的过去与未来是一一对应的，因此该监督是有意义的。然而，在MS的设置下，多条序列的过去仅对应一条序列的未来，导致不是一一对应的关系。在代码中，我们仅使用了一个线性层将多条序列的得分映射到一条序列上，这样的监督可能会存在一定问题。

另外，在MS的条件下，原本数据的归一化和反归一化操作也无法正常进行，因为过去和未来的通道维度不同，而我们的模型期望序列与基底的交互是在一个归一化的空间中进行的，这可能也会造成性能的下降。

期待您的理解与支持。如有进一步问题，欢迎随时联系。
