### ISSUE TITLE
关于基的确定

### ISSUE THREAD

**Issue by Like-h** [nzl5116190/Basisformer#3]
您好，看了您的论文和相关代码，我注意到您对基的获取是通过将时间戳的相对位置进行线性映射得到的吗？这里面的基是否需要满足互不相关的性质呢？

**Comment by nzl5116190** [comment]
**Answer (English Version)**
Hello!
Thank you for your interest in our paper and code. In our study, the bases are indeed obtained by normalizing the timestamps to the [0,1] interval and then performing a linear mapping on the relative timestamps.
Regarding whether the bases need to be mutually uncorrelated, we have two observations and design philosophies. Firstly, we found that when the number of bases is small, the correlation between the bases learned through our framework is generally low. However, as the number of bases increases to a certain extent, some bases with higher correlation appear due to redundancy among them. Therefore, a certain balance in the number of bases is necessary. Secondly, in our design process, we also experimented with introducing a loss function related to the orthogonality of the bases to constrain the optimization space of the bases. One approach was to consider the average of the cosine similarities of all pairs of base vectors as a loss function. However, this method did not perform well when optimized jointly with the prediction loss function. This might be due to the presence of some features in fixed time series datasets that are not completely orthogonal. Overly restricting the distribution of the solution space might hinder the model's ability to capture features beneficial for prediction. This is also why we later adopted a contrastive loss function. The contrastive loss function can differentiate between different base vectors while not being overly restrictive on the solution space, allowing for better adaptability to the data characteristics.

**回答（中文版） / Answer (Chinese Version)**
您好！ 感谢您对我们论文和代码的关注。
在我们的研究中，基底的获取确实是通过将时间戳归一化至[0,1]区间，并对相对时间戳执行线性映射来实现的。 
至于基底是否需要满足互不相关的性质，这方面我们有两点发现和设计理念。首先，我们观察到，在基底数量较少时，通过我们的框架得到的基底相关性通常较低。然而，当基底数量增加到一定程度后，会出现一些相关性较高的基底，这主要是因为基底之间出现了冗余。所以，基底的数量需要进行一定的权衡。其次，在设计过程中，我们也曾尝试通过引入一个关于基底正交性的损失函数来限制基底的优化空间。例如，考虑采用所有两两基底向量余弦相似度的平均值作为损失函数。不过，这种做法与预测损失函数的联合优化效果并不理想。这可能是因为在固定的时间序列数据集中，通常会存在一些并非完全正交的特征，过分限制解空间的分布可能不利于模型捕捉对预测有益的相关特征。这也是我们后续采用对比损失函数形式的原因。对比损失函数既可以区分不同基底向量，又对解空间的限制不那么严格，从而更好地适应数据特性。
